# Generated by Django 2.0.4 on 2019-04-28 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atracao',
            name='idade_minima',
            field=models.IntegerField(),
        ),
    ]
